"""add allocations and assets tables

Revision ID: fa7e67ea6a3d
Revises: 1f8ff19622d3
Create Date: 2025-08-11 20:30:09.044574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7e67ea6a3d'
down_revision: Union[str, Sequence[str], None] = '1f8ff19622d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allocations', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('allocations', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allocations', 'asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('allocations', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
