from dotenv import load_dotenv
import os

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))

DATABASE_URL = os.getenv("DATABASE_URL")

YFINANCE_DEFAULT_PERIOD= os.getenv("YFINANCE_DEFAULT_PERIOD=1d")
YFINANCE_DEFAULT_INTERVAL= os.getenv("YFINANCE_DEFAULT_INTERVAL=1m")

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
